/*
 * NotepadEntry.swift
 *
 * GRDB record mirroring the `notepad_entries` table in
 * design-system/migrations/v1_initial.sql. Columns stay snake_case (the
 * `CodingKeys` enum owns that mapping) so GRDB emits SQL that's byte-for-byte
 * compatible with what Android's Room side emits.
 *
 * Schema alignment with Android: this iOS port executes a verbatim copy of
 * the notepad section of v1_initial.sql in `ReleafDatabase.swift` (including
 * CHECK constraints, the FTS5 virtual table, and its triggers) — it doesn't
 * rely on GRDB's column-from-Swift DDL inference. Any future schema change
 * should land as a new migration in both clients simultaneously.
 *
 * Timestamps are ISO-8601 strings (not Date), matching the TEXT columns on
 * disk. This avoids platform-specific Date→String drift when rows round-trip
 * through Drive.
 *
 * Protocol choice: `PersistableRecord` (not `MutablePersistableRecord`) —
 * our primary key is a UUIDv7 generated by the app, not an auto-incremented
 * rowid, so we don't need GRDB's mutating didInsert stamp-back.
 */

import Foundation
import GRDB

public struct NotepadEntry: Codable, FetchableRecord, PersistableRecord,
                            Identifiable, Equatable, Sendable {

    /// Table name matches the SQL exactly.
    public static let databaseTableName = "notepad_entries"

    // MARK: Columns

    /// UUIDv7 — generated via `Uuidv7.generate()` so ids sort chronologically
    /// and can be used as a cheap insertion-order proxy in `ORDER BY id`.
    public var id: String

    /// Scoping column; shared with `daily_logs` for the by-date join the
    /// home screen's day summary uses.
    public var userId: String

    /// `YYYY-MM-DD` (local date this entry is filed under). The SQL CHECK
    /// constraint GLOBs for exactly this shape; keep it that way.
    public var entryDate: String

    public var projectId: String?

    public var title: String?

    /// Canonical CommonMark. Empty string is valid.
    public var notes: String

    /// JSON array of `NotepadContact`. Always a JSON string, never null;
    /// default `[]`. See `Attachments.swift` for the value type.
    public var contacts: String

    /// JSON array of `GeoLocation`. Always a JSON string, never null; default `[]`.
    public var locations: String

    /// JSON array of `NotepadTodo`. Same shape as the pages table's
    /// `todos` column on Android — surfaced by the notepad editor's
    /// TODOS section.
    public var todos: String

    /// JSON array of Attachment (photos + scans). Same shape as pages.
    /// Photos and scanned-PDF files are copied into the app's files
    /// directory at capture time; the URI stored here is the file:// URL.
    public var attachments: String

    /// Allow empty notes + no contacts + no locations on save.
    /// Stored as INTEGER 0/1 — GRDB handles the Bool↔Int bridge automatically.
    public var allowBlankContent: Bool

    /// JSON: `{local_notes, remote_notes, remote_updated_at}` or nil.
    public var conflictStub: String?

    public var driveFileId: String?

    /// ISO-8601 UTC with ms (e.g. `2026-04-21T10:15:30.123Z`). See `IsoClock`.
    public var createdAt: String

    public var updatedAt: String

    /// `true` = needs upload to Drive; cleared by the sync worker.
    public var dirty: Bool

    /// ISO-8601 UTC when soft-deleted; nil = active.
    public var deletedAt: String?

    // MARK: - Codable/Column mapping

    /// snake_case column names match the shared schema on disk. GRDB reads
    /// these as the actual column names because it uses `CodingKeys` as the
    /// column directory for Codable records.
    public enum CodingKeys: String, CodingKey {
        case id
        case userId             = "user_id"
        case entryDate          = "entry_date"
        case projectId          = "project_id"
        case title
        case notes
        case contacts
        case locations
        case todos
        case attachments
        case allowBlankContent  = "allow_blank_content"
        case conflictStub       = "conflict_stub"
        case driveFileId        = "drive_file_id"
        case createdAt          = "created_at"
        case updatedAt          = "updated_at"
        case dirty
        case deletedAt          = "deleted_at"
    }

    // MARK: - Init

    public init(
        id: String,
        userId: String,
        entryDate: String,
        projectId: String? = nil,
        title: String? = nil,
        notes: String = "",
        contacts: String = "[]",
        locations: String = "[]",
        todos: String = "[]",
        attachments: String = "[]",
        allowBlankContent: Bool = false,
        conflictStub: String? = nil,
        driveFileId: String? = nil,
        createdAt: String,
        updatedAt: String,
        dirty: Bool = true,
        deletedAt: String? = nil
    ) {
        self.id = id
        self.userId = userId
        self.entryDate = entryDate
        self.projectId = projectId
        self.title = title
        self.notes = notes
        self.contacts = contacts
        self.locations = locations
        self.todos = todos
        self.attachments = attachments
        self.allowBlankContent = allowBlankContent
        self.conflictStub = conflictStub
        self.driveFileId = driveFileId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.dirty = dirty
        self.deletedAt = deletedAt
    }
}
