/*
 * DailyPlants.swift
 *
 * Single source of truth for the Ayurvedic plant catalogue is
 * `design-system/plants.json` (90 plants today, append-only). That
 * file is symlinked into `Notepad/Resources/plants.json` and declared
 * in `Package.swift` as a copied resource on the `ReleafData` target,
 * so it ships in the bundle and `DailyPlants` can read it at runtime
 * via `Bundle.module`.
 *
 * Was previously generated by `design-system/scripts/generate-tokens.mjs`
 * — the generator step is no longer needed (and CI no longer needs to
 * run it for plant data) because both platforms now point at the same
 * JSON source. Edits to `plants.json` take effect on the next build
 * automatically.
 *
 * Loading is lazy + cached: the JSON is parsed exactly once on first
 * access to `all` (or to anything that calls `all` transitively, e.g.
 * `forToday`). Subsequent accesses hit the in-memory snapshot.
 */

import Foundation

/// One ayurvedic plant in the daily-rotation list.
public struct DailyPlant: Codable, Equatable, Sendable {
    /// Sanskrit name shown as the page title (lowercase serif).
    public let name: String
    /// English / common name shown in a parenthetical after the
    /// Sanskrit. Empty string when the Sanskrit name is already the
    /// recognised English form.
    public let commonName: String
    /// One-line poetic descriptor. Sits at the head of the subtitle.
    public let epithet: String
    /// Comma-separated practical uses. Sits after the epithet,
    /// separated by a center dot.
    public let usedFor: String

    public init(name: String, commonName: String, epithet: String, usedFor: String) {
        self.name = name
        self.commonName = commonName
        self.epithet = epithet
        self.usedFor = usedFor
    }
}

/// Daily-plant rotation source for the page header. `forToday(date)`
/// returns one plant per calendar day (deterministic), and `all`
/// exposes the full ordered list for callers (notepad seeding) that
/// pick by entry id rather than by date.
public enum DailyPlants {

    /// Stable, append-only list of every plant in the catalogue.
    /// Lazy-parsed from the bundled `plants.json` on first access.
    public static let all: [DailyPlant] = {
        guard let url = Bundle.module.url(forResource: "plants", withExtension: "json") else {
            preconditionFailure(
                "DailyPlants: could not locate `plants.json` in Bundle.module — " +
                "check the resources declaration on the ReleafData target in Package.swift."
            )
        }
        do {
            let data = try Data(contentsOf: url)
            let plants = try JSONDecoder().decode([DailyPlant].self, from: data)
            precondition(!plants.isEmpty, "DailyPlants: plants.json decoded to an empty array")
            return plants
        } catch {
            preconditionFailure(
                "DailyPlants: failed to load `plants.json`: \(error)"
            )
        }
    }()

    /// The plant for `date`, default today. Selection is
    /// `(dayOfYear - 1) % count` against the user's calendar — stable
    /// within a day, rotates across days.
    public static func forToday(
        date: Date = Date(),
        calendar: Calendar = .current
    ) -> DailyPlant {
        let pool = all
        let dayOfYear = calendar.ordinality(of: .day, in: .year, for: date) ?? 1
        let index = (dayOfYear - 1) % pool.count
        return pool[index]
    }
}
