/*
 * shared/android/shared/designsystem/build.gradle.kts
 *
 * Build config for the :shared:designsystem library module. Holds the
 * Compose tokens + truly-shared Compose components used by both Releaf
 * and (eventually) QuickInk:
 *
 *   Tokens — `app.releaf.mobile.ui.theme` package:
 *     - AppAccent.kt
 *     - AppColors.generated.kt   (regenerated by token pipeline)
 *     - AppFontWeights.kt
 *     - AppMetrics.generated.kt  (regenerated by token pipeline)
 *     - AppSpacing.kt
 *     - AppTheme.kt
 *     - AppTypography.kt
 *     - UiPreferences.kt
 *
 *   Components — `app.releaf.mobile.ui.components` package:
 *     - AppButton.kt
 *     - Breadcrumbs.kt
 *     - DotGridBackground.kt
 *     - LeafDropletGlyph.kt        (rendering only; CaptureMode tinter
 *                                    stays in Releaf — see PR #4h notes)
 *     - PageHeaderControls.kt
 *
 * Releaf-specific files that intentionally STAY in the app module:
 *   Tokens:    DailyPlant, DailyPlants, ReleafImpact, ReleafReadEstimate
 *   Tinter:    leafDropletTintFor(CaptureMode)  — needs CaptureMode
 *   Components: ActivityTimeline, BottomNav, CaptureFab, CaptureTabBar,
 *               LeafColorPicker (uses ShelfTheme), NotebookRow,
 *               PagePreviewRow, PaperSavedSheet, QuickCaptureSheet,
 *               ReLeafStrip, ReleafLogo, ReleafLogoRow, ShelfTheme,
 *               StatGrid (uses CaptureMode), and so on.
 *
 * Mirror of iOS PR #4g (`ReleafCoreDesignSystem`); cut line matches
 * that PR's "what stays / what moves" list line-for-line where the two
 * platforms have an equivalent file.
 */

import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.compose.compiler)
}

android {
    namespace  = "app.releaf.shared.designsystem"
    compileSdk = 36

    defaultConfig {
        minSdk = 26
    }

    buildFeatures {
        compose = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {
    // Compose. Same surface the Releaf app target pulls in — runtime +
    // ui-graphics come transitively through the BOM. Previews + tooling
    // are debug-only.
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.foundation)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons)
    implementation(libs.compose.ui.tooling.preview)
    debugImplementation(libs.compose.ui.tooling)

    // UiPreferences uses kotlinx.coroutines Flow types for the
    // settings-state stream the theme reads from.
    implementation(libs.coroutines.android)
}
