/*
 * DailyPlants.kt
 *
 * Single source of truth for the Ayurvedic plant catalogue is
 * `design-system/plants.json` (90 plants today, append-only). That
 * file is symlinked into `app/src/main/assets/plants.json` so the APK
 * carries it; `DailyPlants` reads it lazily on first access through
 * the application Context that `ReleafApp.onCreate` hands to
 * [initialize].
 *
 * Was previously generated by `design-system/scripts/generate-tokens.mjs`
 * — the generator step is no longer needed (and CI no longer needs to
 * run it for plant data) because both platforms now point at the
 * single JSON source. Edits to `plants.json` take effect on the next
 * build automatically.
 */

package app.releaf.mobile.ui.theme

import android.content.Context
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.time.LocalDate

/** One ayurvedic plant in the daily-rotation list. */
@Serializable
data class DailyPlant(
    /** Sanskrit name shown as the page title (lowercase serif). */
    val name: String,
    /** English / common name shown in a parenthetical after the
     *  Sanskrit. Empty string when the Sanskrit name is already the
     *  recognised English form. */
    val commonName: String,
    /** One-line poetic descriptor. Sits at the head of the subtitle. */
    val epithet: String,
    /** Comma-separated practical uses. Sits after the epithet,
     *  separated by a center dot. */
    val usedFor: String,
)

/**
 * Daily-plant rotation source for the page header. `forToday(date)`
 * returns one plant per calendar day (deterministic), and `all`
 * exposes the full ordered list for callers (notepad seeding) that
 * pick by entry id rather than by date.
 *
 * The list is parsed once from `assets/plants.json` and cached.
 * `ReleafApp.onCreate` calls [initialize] before any UI surface
 * touches the catalogue, so accessors are non-suspending and never
 * block on disk after init.
 */
object DailyPlants {

    /** Lazy-init backing field. Populated by [initialize]; reads
     *  before init throw a clear error rather than returning empty
     *  silently (every caller assumes a non-empty list). */
    @Volatile private var _all: List<DailyPlant>? = null

    private val parser = Json {
        ignoreUnknownKeys = true
        isLenient         = false
    }

    /** Parse `assets/plants.json` once and cache. Idempotent — calling
     *  twice is a no-op. Wrapped in synchronized so a worst-case
     *  race during ReleafApp.onCreate can't double-parse. */
    @Synchronized
    fun initialize(context: Context) {
        if (_all != null) return
        val bytes = context.applicationContext.assets.open("plants.json")
            .use { it.readBytes() }
        val text  = String(bytes, Charsets.UTF_8)
        _all = parser.decodeFromString(
            kotlinx.serialization.builtins.ListSerializer(DailyPlant.serializer()),
            text,
        )
    }

    /** Stable, append-only list of every plant in the catalogue. */
    val all: List<DailyPlant>
        get() = _all
            ?: error("DailyPlants.all read before initialize() — call initialize(context) in Application.onCreate()")

    /** The plant for [date], default today. Selection is
     *  `(dayOfYear - 1) % count` against the user's local calendar —
     *  stable within a day, rotates across days. */
    fun forToday(date: LocalDate = LocalDate.now()): DailyPlant {
        val pool = all
        val index = (date.dayOfYear - 1).mod(pool.size)
        return pool[index]
    }
}
