#!/usr/bin/env bash
#
# phase4h-android-designsystem-extract.sh
#
# PR #4h — extract Android :shared:designsystem (the largest sub-PR
# in the PR #4 sequence on the Android side, mirroring iOS PR #4g).
# Moves the design tokens + truly shared Compose components into the
# new :shared:designsystem module so QuickInk can depend on them.
#
# What moves into :shared:designsystem:
#
#   Tokens (8 files) — package `app.releaf.mobile.ui.theme`:
#     - AppAccent.kt
#     - AppColors.generated.kt    (regenerated by token pipeline)
#     - AppFontWeights.kt
#     - AppMetrics.generated.kt   (regenerated by token pipeline)
#     - AppSpacing.kt
#     - AppTheme.kt
#     - AppTypography.kt
#     - UiPreferences.kt
#
#   Shared components (5 files) — package `app.releaf.mobile.ui.components`:
#     - AppButton.kt
#     - Breadcrumbs.kt
#     - DotGridBackground.kt
#     - LeafDropletGlyph.kt        (rendering only; the
#                                    `leafDropletTintFor(CaptureMode)`
#                                    helper stays in the app target as
#                                    a sibling file `LeafDropletGlyphTints.kt`
#                                    — see iOS PR #4g for the same split)
#     - PageHeaderControls.kt
#
# Plus 2 deferred-from-PR-#4f editor views moved into :shared:notes
# (now safe — they were waiting on :shared:designsystem to ship):
#   - editor/RichTextFormatBar.kt
#   - editor/EditorModeToggle.kt
#
# What stays in apps/releaf (Releaf-specific):
#   Tokens:
#     - DailyPlant.kt
#     - DailyPlants.kt
#     - ReleafImpact.kt           (Trees Saved hero shape)
#     - ReleafReadEstimate.kt     (Releaf-specific feature)
#   Components:
#     - ActivityTimeline, BottomNav, CaptureFab, CaptureTabBar,
#       LeafColorPicker (uses ShelfTheme), NotebookRow,
#       PagePreviewRow, PaperSavedSheet, QuickCaptureSheet,
#       ReLeafStrip, ReleafLogo, ReleafLogoRow, ShelfTheme,
#       StatGrid (uses CaptureMode), CaptureMode, and so on.
#     - LeafDropletGlyphTints.kt  (NEW — CaptureMode → tint helper
#                                    that used to live in
#                                    LeafDropletGlyph.kt)
#
# Editor views still deferred (NOT moved this PR):
#   - editor/NotesEditorSheet.kt — imports `data.notebook.{Stroke,SubPage}`
#     which still live in the app target's notebook layer. Moves once
#     the notebook data layer extracts.
#   - There is no Android counterpart to iOS `EntryDateRow.swift` —
#     the date control is inline inside `NotepadEditorScreen.kt`.
#
# What this script does:
#   1. git mv 8 design tokens into :shared:designsystem.
#   2. git mv 4 shared components into :shared:designsystem.
#   3. git mv LeafDropletGlyph.kt (now containing only the composable
#      after the in-place split) into :shared:designsystem.
#   4. git mv 2 editor views into :shared:notes.
#   5. Stage settings.gradle.kts + app/build.gradle.kts +
#      :shared:notes/build.gradle.kts + new files.
#
# Already in working tree (NOT done by this script):
#   - shared/android/settings.gradle.kts
#       (EDITED — adds `:shared:designsystem` include + projectDir)
#   - shared/android/shared/designsystem/build.gradle.kts
#       (NEW — Compose-enabled Android library module config)
#   - apps/releaf/android/app/build.gradle.kts
#       (EDITED — adds `implementation(project(":shared:designsystem"))`)
#   - shared/android/shared/notes/build.gradle.kts
#       (EDITED — adds compose-compiler plugin, buildFeatures.compose,
#        :shared:designsystem dep, Compose libs, rich-editor lib;
#        updates the file-header doc to describe the PR #4h additions)
#   - apps/releaf/android/app/src/main/java/app/releaf/mobile/ui/components/LeafDropletGlyph.kt
#       (EDITED IN PLACE — drops the `leafDropletTintFor(CaptureMode)`
#        helper + its `AppColors` import; keeps only the rendering
#        composable. File is then git-mv'd into :shared:designsystem
#        by this script)
#   - apps/releaf/android/app/src/main/java/app/releaf/mobile/ui/components/LeafDropletGlyphTints.kt
#       (NEW — sibling file in the same Kotlin package holding the
#        `leafDropletTintFor(CaptureMode)` helper that just left
#        LeafDropletGlyph.kt; stays in the Releaf app target because
#        CaptureMode is Releaf-specific)
#
# Usage:
#   bash scripts/phase4h-android-designsystem-extract.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# ─── Pre-flight ────────────────────────────────────────────────────────

if [[ ! -d .git ]]; then
    echo "ERROR: not in a git repo" >&2
    exit 2
fi
if [[ -f .git/index.lock ]]; then
    echo "ERROR: stale .git/index.lock present. Remove it first." >&2
    exit 2
fi

PRE_REQS=(
    "shared/android/settings.gradle.kts"
    "shared/android/shared/designsystem/build.gradle.kts"
    "apps/releaf/android/app/build.gradle.kts"
    "shared/android/shared/notes/build.gradle.kts"
    "apps/releaf/android/app/src/main/java/app/releaf/mobile/ui/components/LeafDropletGlyphTints.kt"
)
for p in "${PRE_REQS[@]}"; do
    [[ -f "$p" ]] || { echo "ERROR: missing pre-edited file: $p" >&2; exit 2; }
done

THEME_SRC="apps/releaf/android/app/src/main/java/app/releaf/mobile/ui/theme"
COMP_SRC="apps/releaf/android/app/src/main/java/app/releaf/mobile/ui/components"
EDITOR_SRC="$COMP_SRC/editor"

TOKENS=(
    "AppAccent.kt"
    "AppColors.generated.kt"
    "AppFontWeights.kt"
    "AppMetrics.generated.kt"
    "AppSpacing.kt"
    "AppTheme.kt"
    "AppTypography.kt"
    "UiPreferences.kt"
)
COMPONENTS=(
    "AppButton.kt"
    "Breadcrumbs.kt"
    "DotGridBackground.kt"
    "LeafDropletGlyph.kt"
    "PageHeaderControls.kt"
)
EDITOR_VIEWS=(
    "RichTextFormatBar.kt"
    "EditorModeToggle.kt"
)

for f in "${TOKENS[@]}";        do [[ -f "$THEME_SRC/$f"  ]] || { echo "ERROR: missing token $f"     >&2; exit 2; }; done
for f in "${COMPONENTS[@]}";    do [[ -f "$COMP_SRC/$f"   ]] || { echo "ERROR: missing component $f" >&2; exit 2; }; done
for f in "${EDITOR_VIEWS[@]}";  do [[ -f "$EDITOR_SRC/$f" ]] || { echo "ERROR: missing editor view $f" >&2; exit 2; }; done

# Destinations. Kotlin packages stay the same as the source — moving a
# file across modules doesn't require renaming its package, and keeping
# them stable means call sites need zero import changes.
DEST_DS="shared/android/shared/designsystem/src/main/kotlin"
DEST_THEME="$DEST_DS/app/releaf/mobile/ui/theme"
DEST_COMP="$DEST_DS/app/releaf/mobile/ui/components"
DEST_NOTES_EDITOR="shared/android/shared/notes/src/main/kotlin/app/releaf/mobile/ui/components/editor"

mkdir -p "$DEST_THEME"
mkdir -p "$DEST_COMP"
mkdir -p "$DEST_NOTES_EDITOR"

echo "Pre-flight passed."

# ─── 1. Move tokens into :shared:designsystem ─────────────────────────

for f in "${TOKENS[@]}"; do
    git mv "$THEME_SRC/$f" "$DEST_THEME/$f"
done
echo "Moved 8 tokens into :shared:designsystem."

# ─── 2. Move shared components (incl. LeafDropletGlyph) ──────────────

for f in "${COMPONENTS[@]}"; do
    git mv "$COMP_SRC/$f" "$DEST_COMP/$f"
done
echo "Moved 5 components (incl. split LeafDropletGlyph) into :shared:designsystem."

# ─── 3. Move 2 editor views into :shared:notes ────────────────────────

for f in "${EDITOR_VIEWS[@]}"; do
    git mv "$EDITOR_SRC/$f" "$DEST_NOTES_EDITOR/$f"
done
echo "Moved 2 editor views into :shared:notes."

# ─── 4. Stage everything else ─────────────────────────────────────────

git add \
    shared/android/settings.gradle.kts \
    shared/android/shared/designsystem/build.gradle.kts \
    apps/releaf/android/app/build.gradle.kts \
    shared/android/shared/notes/build.gradle.kts \
    apps/releaf/android/app/src/main/java/app/releaf/mobile/ui/components/LeafDropletGlyphTints.kt

echo ""
echo "═════════════════════════════════════════════════════════"
echo " PR #4h extract complete. Nothing committed yet."
echo "═════════════════════════════════════════════════════════"
echo ""
echo "Review with:"
echo "  git status"
echo "  git diff --staged --stat"
echo ""
echo "Verify on host:"
echo "  cd shared/android"
echo "  ./gradlew :apps:releaf:assembleDebug 2>&1 | tail -60"
echo ""
echo "Suggested commit:"
echo ""
echo "  PR #4h: extract Android :shared:designsystem (tokens + components)"
echo ""
echo "  - git mv 8 tokens (AppAccent, AppColors.generated, AppFontWeights,"
echo "    AppMetrics.generated, AppSpacing, AppTheme, AppTypography,"
echo "    UiPreferences) and 4 shared components (AppButton, Breadcrumbs,"
echo "    DotGridBackground, PageHeaderControls) into :shared:designsystem."
echo "  - Split LeafDropletGlyph: rendering composable goes shared, the"
echo "    \`leafDropletTintFor(CaptureMode)\` helper stays in the app target"
echo "    as a sibling file in the same Kotlin package. Same split iOS PR"
echo "    #4g used for the equivalent type."
echo "  - Move 2 editor views (RichTextFormatBar, EditorModeToggle) into"
echo "    :shared:notes — they were waiting on :shared:designsystem to"
echo "    ship (PR #4f deferral). NotesEditorSheet stays deferred until"
echo "    the notebook data layer extracts."
echo "  - Add :shared:designsystem to settings.gradle.kts and to the"
echo "    Releaf app's deps. Add Compose deps + :shared:designsystem dep"
echo "    to :shared:notes so the moved editor views compile there."
echo ""
echo "  Mirrors iOS PR #4g cut line where the platforms have equivalents."
echo "  Closes the Android DesignSystem extract; only :shared:scan (PR"
echo "  #4j) remains before PR #4 fully closes."
echo ""
echo "  Verified with ./gradlew :apps:releaf:assembleDebug."
echo ""
