#!/usr/bin/env bash
#
# phase4g-ios-designsystem-extract.sh
#
# PR #4g — extract iOS ReleafCoreDesignSystem (the largest sub-PR
# in the PR #4 sequence). Moves the generated tokens + the truly
# shared component library into the ReleafCoreDesignSystem target.
#
# What moves into ReleafCoreDesignSystem:
#
#   Tokens (8 files):
#     - AccentPalette.swift
#     - AppColors.generated.swift   (regenerated by token pipeline)
#     - AppFontWeight+Env.swift
#     - AppMetrics.generated.swift  (regenerated by token pipeline)
#     - AppShadow.swift
#     - AppSpacing.swift
#     - AppTypography.swift
#     - UiPreferences.swift
#
#   Shared components (5 files in Components/):
#     - AppButton.swift
#     - Breadcrumbs.swift
#     - Card.swift
#     - DotGridBackground.swift
#     - PageHeaderControls.swift
#
# What stays in Releaf/DesignSystem (Releaf-specific):
#   Tokens:
#     - CaptureMode.swift            (Releaf's 8 capture modes)
#     - DailyPlant.swift             (plant catalog data type)
#     - ReleafImpact.swift           (Trees Saved hero shape)
#     - ReleafReadEstimate.swift     (Releaf-specific feature)
#   Components:
#     - ActivityTimeline, BottomNav, CaptureFAB, CaptureTabBar,
#       LeafColorPicker (uses ShelfTheme), LeafDropletGlyph,
#       NotebookRow, PagePreviewRow, PaperSavedSheet, QuickCaptureSheet,
#       ReLeafStrip, ReleafLogo, ReleafLogoRow, ShelfTheme,
#       StatGrid (uses CaptureMode)
#
# Plus 4 deferred-from-PR-#4e editor views moved into ReleafCoreNotes
# (now safe — they were waiting on ReleafCoreDesignSystem to ship):
#   - RichTextFormatBar.swift
#   - EditorModeToggle.swift
#   - EntryDateRow.swift
#   - NotesEditorSheet.swift
#
# What this script does:
#   1. git mv 13 design-system files into ReleafCoreDesignSystem.
#   2. git mv 4 editor views into ReleafCoreNotes.
#   3. git rm ReleafCoreDesignSystem/Placeholder.swift.
#   4. Stage Package.swift edits + the new shim file + token-script
#      path updates.
#
# Already in working tree:
#   - apps/releaf/ios/Package.swift                (EDITED)
#   - apps/releaf/ios/Releaf/DesignSystem/ReleafCoreDesignSystemReexport.swift (NEW)
#   - shared/design-system/scripts/generate-tokens.mjs (EDITED — IOS_REL paths)
#   - shared/design-system/scripts/check-tokens.sh     (EDITED — IOS_REL path)
#
# Usage:
#   bash scripts/phase4g-ios-designsystem-extract.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

if [[ ! -d .git ]]; then
    echo "ERROR: not in a git repo" >&2
    exit 2
fi
if [[ -f .git/index.lock ]]; then
    echo "ERROR: stale .git/index.lock present. Remove it first." >&2
    exit 2
fi

# Pre-PR work that should already exist:
PRE_REQS=(
    "apps/releaf/ios/Releaf/DesignSystem/ReleafCoreDesignSystemReexport.swift"
)
for p in "${PRE_REQS[@]}"; do
    [[ -f "$p" ]] || { echo "ERROR: missing $p" >&2; exit 2; }
done

# Tokens to move into ReleafCoreDesignSystem flat root:
TO_MOVE_TOKENS=(
    "apps/releaf/ios/Releaf/DesignSystem/AccentPalette.swift"
    "apps/releaf/ios/Releaf/DesignSystem/AppColors.generated.swift"
    "apps/releaf/ios/Releaf/DesignSystem/AppFontWeight+Env.swift"
    "apps/releaf/ios/Releaf/DesignSystem/AppMetrics.generated.swift"
    "apps/releaf/ios/Releaf/DesignSystem/AppShadow.swift"
    "apps/releaf/ios/Releaf/DesignSystem/AppSpacing.swift"
    "apps/releaf/ios/Releaf/DesignSystem/AppTypography.swift"
    "apps/releaf/ios/Releaf/DesignSystem/UiPreferences.swift"
)
TO_MOVE_COMPONENTS=(
    "apps/releaf/ios/Releaf/DesignSystem/Components/AppButton.swift"
    "apps/releaf/ios/Releaf/DesignSystem/Components/Breadcrumbs.swift"
    "apps/releaf/ios/Releaf/DesignSystem/Components/Card.swift"
    "apps/releaf/ios/Releaf/DesignSystem/Components/DotGridBackground.swift"
    "apps/releaf/ios/Releaf/DesignSystem/Components/PageHeaderControls.swift"
)
TO_MOVE_NOTES_VIEWS=(
    "apps/releaf/ios/Releaf/Features/Notepad/RichTextFormatBar.swift"
    "apps/releaf/ios/Releaf/Features/Notepad/EditorModeToggle.swift"
    "apps/releaf/ios/Releaf/Features/Notepad/EntryDateRow.swift"
    "apps/releaf/ios/Releaf/Features/Notepad/NotesEditorSheet.swift"
)

for p in "${TO_MOVE_TOKENS[@]}" "${TO_MOVE_COMPONENTS[@]}" "${TO_MOVE_NOTES_VIEWS[@]}"; do
    [[ -f "$p" ]] || { echo "ERROR: missing source $p" >&2; exit 2; }
done

if [[ ! -f shared/ios/ReleafCore/Sources/ReleafCoreDesignSystem/Placeholder.swift ]]; then
    echo "ERROR: ReleafCoreDesignSystem/Placeholder.swift missing — already extracted?" >&2
    exit 2
fi

mkdir -p shared/ios/ReleafCore/Sources/ReleafCoreDesignSystem/Components
mkdir -p shared/ios/ReleafCore/Sources/ReleafCoreNotes

echo "Pre-flight passed."

# ─── 1. Move tokens ───────────────────────────────────────────────────
DEST_DS="shared/ios/ReleafCore/Sources/ReleafCoreDesignSystem"
for f in "${TO_MOVE_TOKENS[@]}"; do
    base="$(basename "$f")"
    git mv "$f" "$DEST_DS/$base"
done
echo "Moved 8 design tokens into ReleafCoreDesignSystem."

# ─── 2. Move shared components ────────────────────────────────────────
for f in "${TO_MOVE_COMPONENTS[@]}"; do
    base="$(basename "$f")"
    git mv "$f" "$DEST_DS/Components/$base"
done
echo "Moved 5 components into ReleafCoreDesignSystem/Components/."

# ─── 3. Move 4 editor views into ReleafCoreNotes (PR #4e deferred set) ──
DEST_NOTES="shared/ios/ReleafCore/Sources/ReleafCoreNotes"
for f in "${TO_MOVE_NOTES_VIEWS[@]}"; do
    base="$(basename "$f")"
    git mv "$f" "$DEST_NOTES/$base"
done
echo "Moved 4 editor views into ReleafCoreNotes."

# ─── 4. Drop the ReleafCoreDesignSystem placeholder ───────────────────
git rm "$DEST_DS/Placeholder.swift"
echo "Removed ReleafCoreDesignSystem placeholder."

# ─── 5. Stage everything else ─────────────────────────────────────────
git add \
  apps/releaf/ios/Package.swift \
  apps/releaf/ios/Releaf/DesignSystem/ReleafCoreDesignSystemReexport.swift \
  shared/design-system/scripts/generate-tokens.mjs \
  shared/design-system/scripts/check-tokens.sh

echo ""
echo "═════════════════════════════════════════════════════════"
echo " PR #4g extract complete. Nothing committed yet."
echo "═════════════════════════════════════════════════════════"
echo ""
echo "Verify on Mac:"
echo "  # Sanity: regenerate tokens, confirm they land at the new path"
echo "  node shared/design-system/scripts/generate-tokens.mjs"
echo "  bash shared/design-system/scripts/check-tokens.sh"
echo "  # Build:"
echo "  cd apps/releaf/ios"
echo "  xcodebuild -scheme ReleafFeatures \\"
echo "    -destination 'generic/platform=iOS Simulator' build 2>&1 \\"
echo "    | grep -E 'error:' | head -30"
echo ""
echo "Suggested commit:"
echo ""
echo "  PR #4g: extract iOS ReleafCoreDesignSystem (tokens + components)"
echo ""
echo "  - git mv 8 design tokens (AccentPalette, AppColors.generated,"
echo "    AppFontWeight+Env, AppMetrics.generated, AppShadow, AppSpacing,"
echo "    AppTypography, UiPreferences) and 5 shared components"
echo "    (AppButton, Breadcrumbs, Card, DotGridBackground,"
echo "    PageHeaderControls) into ReleafCoreDesignSystem."
echo "  - Move 4 editor views (RichTextFormatBar, EditorModeToggle,"
echo "    EntryDateRow, NotesEditorSheet) into ReleafCoreNotes — they"
echo "    were waiting on ReleafCoreDesignSystem to ship (PR #4e deferral)."
echo "  - Update generate-tokens.mjs + check-tokens.sh to write/check"
echo "    the new ReleafCoreDesignSystem paths."
echo "  - Add ReleafDesignSystem/ReleafCoreDesignSystemReexport.swift"
echo "    so existing \`import ReleafDesignSystem\` callers keep working."
echo "  - ReleafDesignSystem target now depends on ReleafCoreDesignSystem"
echo "    so the Releaf-only files left here (LeafColorPicker w/ ShelfTheme,"
echo "    StatGrid w/ CaptureMode, ReleafLogo, BottomNav, CaptureFAB, etc.)"
echo "    can still reference AppColors / AppText / AppSpacing."
echo "  - Drop ReleafCoreDesignSystem/Placeholder.swift — superseded."
echo ""
echo "  Verified with xcodebuild -scheme ReleafFeatures."
echo ""
